import { Metadata } from 'next';
import Favicon from './favicon.svg';

export const metadata: Metadata = {
  title: 'ToDoTasks.',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: Favicon.src }],
};

export function RootHead(metadata: Metadata) {
  return (
    <>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://rsms.me/inter/inter.css" rel="stylesheet" />
        <link rel="icon" type="image/x-icon" href="./favicon.svg"/>
        <title>ToDoTasks.</title>
      </head>
    </>
  )
}
